repos:
  - repo: local
    hooks:
      - id: html-tidy
        name: HTML Tidy Validation
        entry: /usr/local/bin/tidy
        language: system
        types: [html]
        files: ^(index\.html|resume/index\.html)$
        require_serial: true
        pass_filenames: true
        description: "Validate HTML files using tidy (same as deploy.yml)"
