name: Deploy

on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v2
      - name: Install tidy
        run: sudo apt-get update && sudo apt-get install -y tidy
      - name: Verify HTML
        run: |
          tidy -q -e ./index.html
          tidy -q -e ./resume/index.html
      - name: Set AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.S3_DEPLOY_KEY }}
          aws-secret-access-key: ${{ secrets.S3_DEPLOY_SECRET }}
          aws-region: us-east-1
      - name: Deploy to S3
        run: |
          aws s3 cp ./index.html s3://com.petersobot/index.html
          aws s3 cp ./resume/index.html s3://com.petersobot/resume/index.html
      - name: Invalidate CloudFront cache
        env:
          CLOUDFRONT_DISTRIBUTION_IDS: ${{ secrets.CLOUDFRONT_DISTRIBUTION_IDS }}
        run: |
          for dist in $CLOUDFRONT_DISTRIBUTION_IDS; do
            aws cloudfront create-invalidation --distribution-id "$dist" --paths "/*"
          done
